# Generated by Django 3.2.4 on 2021-06-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_longitude', models.FloatField()),
                ('min_latitude', models.FloatField()),
                ('max_longitude', models.FloatField()),
                ('max_latitude', models.FloatField()),
                ('view_longitude', models.FloatField()),
                ('view_latitude', models.FloatField()),
                ('last_update', models.DateTimeField(editable=False, null=True)),
                ('stored_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('avatar', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('key', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('stored_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_make', models.CharField(max_length=200)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('key', models.CharField(max_length=200, unique=True)),
                ('pano', models.BooleanField()),
                ('stored_at', models.DateTimeField()),
                ('points_in_seq', models.IntegerField()),
                ('region_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.FloatField(null=True)),
                ('image_key', models.CharField(max_length=200, unique=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('direction', models.FloatField(null=True)),
                ('neighbors', models.CharField(max_length=200, null=True)),
                ('weather', models.CharField(default='N.A.', max_length=200)),
                ('filename', models.CharField(max_length=200, null=True)),
                ('sequence_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sequence')),
            ],
        ),
    ]
